sudo: required
services:
    - docker

before_install:
    - docker build -t ramonalisa/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ramonalisa/docker-react npm run test -- --coverage
    