sudo: required
services:
    - docker

before_install:
    - docker build -t ramonalisa/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ramonalisa/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: docker-react
    env: "DockerReact-env"
    bucket_name: elasticbeanstalk-us-west-2-801752849026
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
